// Code generated by MockGen. DO NOT EDIT.
// Source: idempotency.go
//
// Generated by this command:
//
//	mockgen -source=idempotency.go -destination=../mocks/idempotency_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "booking_monitor/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIdempotencyRepository is a mock of IdempotencyRepository interface.
type MockIdempotencyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIdempotencyRepositoryMockRecorder
	isgomock struct{}
}

// MockIdempotencyRepositoryMockRecorder is the mock recorder for MockIdempotencyRepository.
type MockIdempotencyRepositoryMockRecorder struct {
	mock *MockIdempotencyRepository
}

// NewMockIdempotencyRepository creates a new mock instance.
func NewMockIdempotencyRepository(ctrl *gomock.Controller) *MockIdempotencyRepository {
	mock := &MockIdempotencyRepository{ctrl: ctrl}
	mock.recorder = &MockIdempotencyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdempotencyRepository) EXPECT() *MockIdempotencyRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockIdempotencyRepository) Get(ctx context.Context, key string) (*domain.IdempotencyResult, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(*domain.IdempotencyResult)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockIdempotencyRepositoryMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIdempotencyRepository)(nil).Get), ctx, key)
}

// Set mocks base method.
func (m *MockIdempotencyRepository) Set(ctx context.Context, key string, result *domain.IdempotencyResult, fingerprint string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, result, fingerprint)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockIdempotencyRepositoryMockRecorder) Set(ctx, key, result, fingerprint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockIdempotencyRepository)(nil).Set), ctx, key, result, fingerprint)
}
