// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/inventory.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/inventory.go -destination=internal/mocks/mock_inventory_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockInventoryRepository is a mock of InventoryRepository interface.
type MockInventoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryRepositoryMockRecorder
	isgomock struct{}
}

// MockInventoryRepositoryMockRecorder is the mock recorder for MockInventoryRepository.
type MockInventoryRepositoryMockRecorder struct {
	mock *MockInventoryRepository
}

// NewMockInventoryRepository creates a new mock instance.
func NewMockInventoryRepository(ctrl *gomock.Controller) *MockInventoryRepository {
	mock := &MockInventoryRepository{ctrl: ctrl}
	mock.recorder = &MockInventoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventoryRepository) EXPECT() *MockInventoryRepositoryMockRecorder {
	return m.recorder
}

// DeductInventory mocks base method.
func (m *MockInventoryRepository) DeductInventory(ctx context.Context, orderID, eventID, ticketTypeID uuid.UUID, userID, count int, reservedUntil time.Time, amountCents int64, currency string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeductInventory", ctx, orderID, eventID, ticketTypeID, userID, count, reservedUntil, amountCents, currency)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeductInventory indicates an expected call of DeductInventory.
func (mr *MockInventoryRepositoryMockRecorder) DeductInventory(ctx, orderID, eventID, ticketTypeID, userID, count, reservedUntil, amountCents, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeductInventory", reflect.TypeOf((*MockInventoryRepository)(nil).DeductInventory), ctx, orderID, eventID, ticketTypeID, userID, count, reservedUntil, amountCents, currency)
}

// GetInventory mocks base method.
func (m *MockInventoryRepository) GetInventory(ctx context.Context, eventID uuid.UUID) (int, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInventory", ctx, eventID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetInventory indicates an expected call of GetInventory.
func (mr *MockInventoryRepositoryMockRecorder) GetInventory(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInventory", reflect.TypeOf((*MockInventoryRepository)(nil).GetInventory), ctx, eventID)
}

// RevertInventory mocks base method.
func (m *MockInventoryRepository) RevertInventory(ctx context.Context, eventID uuid.UUID, count int, compensationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevertInventory", ctx, eventID, count, compensationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevertInventory indicates an expected call of RevertInventory.
func (mr *MockInventoryRepositoryMockRecorder) RevertInventory(ctx, eventID, count, compensationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevertInventory", reflect.TypeOf((*MockInventoryRepository)(nil).RevertInventory), ctx, eventID, count, compensationID)
}

// SetInventory mocks base method.
func (m *MockInventoryRepository) SetInventory(ctx context.Context, eventID uuid.UUID, count int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetInventory", ctx, eventID, count)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetInventory indicates an expected call of SetInventory.
func (mr *MockInventoryRepositoryMockRecorder) SetInventory(ctx, eventID, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInventory", reflect.TypeOf((*MockInventoryRepository)(nil).SetInventory), ctx, eventID, count)
}
