// Code generated by MockGen. DO NOT EDIT.
// Source: booking_monitor/internal/domain (interfaces: InventoryRepository)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_inventory_repository.go -package=mocks . InventoryRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "booking_monitor/internal/domain"
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockInventoryRepository is a mock of InventoryRepository interface.
type MockInventoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryRepositoryMockRecorder
	isgomock struct{}
}

// MockInventoryRepositoryMockRecorder is the mock recorder for MockInventoryRepository.
type MockInventoryRepositoryMockRecorder struct {
	mock *MockInventoryRepository
}

// NewMockInventoryRepository creates a new mock instance.
func NewMockInventoryRepository(ctrl *gomock.Controller) *MockInventoryRepository {
	mock := &MockInventoryRepository{ctrl: ctrl}
	mock.recorder = &MockInventoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventoryRepository) EXPECT() *MockInventoryRepositoryMockRecorder {
	return m.recorder
}

// DeductInventory mocks base method.
func (m *MockInventoryRepository) DeductInventory(ctx context.Context, orderID, ticketTypeID uuid.UUID, userID, count int, reservedUntil time.Time) (domain.DeductInventoryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeductInventory", ctx, orderID, ticketTypeID, userID, count, reservedUntil)
	ret0, _ := ret[0].(domain.DeductInventoryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeductInventory indicates an expected call of DeductInventory.
func (mr *MockInventoryRepositoryMockRecorder) DeductInventory(ctx, orderID, ticketTypeID, userID, count, reservedUntil any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeductInventory", reflect.TypeOf((*MockInventoryRepository)(nil).DeductInventory), ctx, orderID, ticketTypeID, userID, count, reservedUntil)
}

// DeleteTicketTypeRuntime mocks base method.
func (m *MockInventoryRepository) DeleteTicketTypeRuntime(ctx context.Context, ticketTypeID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTicketTypeRuntime", ctx, ticketTypeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTicketTypeRuntime indicates an expected call of DeleteTicketTypeRuntime.
func (mr *MockInventoryRepositoryMockRecorder) DeleteTicketTypeRuntime(ctx, ticketTypeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTicketTypeRuntime", reflect.TypeOf((*MockInventoryRepository)(nil).DeleteTicketTypeRuntime), ctx, ticketTypeID)
}

// GetInventory mocks base method.
func (m *MockInventoryRepository) GetInventory(ctx context.Context, ticketTypeID uuid.UUID) (int, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInventory", ctx, ticketTypeID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetInventory indicates an expected call of GetInventory.
func (mr *MockInventoryRepositoryMockRecorder) GetInventory(ctx, ticketTypeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInventory", reflect.TypeOf((*MockInventoryRepository)(nil).GetInventory), ctx, ticketTypeID)
}

// RevertInventory mocks base method.
func (m *MockInventoryRepository) RevertInventory(ctx context.Context, ticketTypeID uuid.UUID, count int, compensationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevertInventory", ctx, ticketTypeID, count, compensationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevertInventory indicates an expected call of RevertInventory.
func (mr *MockInventoryRepositoryMockRecorder) RevertInventory(ctx, ticketTypeID, count, compensationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevertInventory", reflect.TypeOf((*MockInventoryRepository)(nil).RevertInventory), ctx, ticketTypeID, count, compensationID)
}

// SetTicketTypeMetadata mocks base method.
func (m *MockInventoryRepository) SetTicketTypeMetadata(ctx context.Context, ticketType domain.TicketType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTicketTypeMetadata", ctx, ticketType)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTicketTypeMetadata indicates an expected call of SetTicketTypeMetadata.
func (mr *MockInventoryRepositoryMockRecorder) SetTicketTypeMetadata(ctx, ticketType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTicketTypeMetadata", reflect.TypeOf((*MockInventoryRepository)(nil).SetTicketTypeMetadata), ctx, ticketType)
}

// SetTicketTypeRuntime mocks base method.
func (m *MockInventoryRepository) SetTicketTypeRuntime(ctx context.Context, ticketType domain.TicketType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTicketTypeRuntime", ctx, ticketType)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTicketTypeRuntime indicates an expected call of SetTicketTypeRuntime.
func (mr *MockInventoryRepositoryMockRecorder) SetTicketTypeRuntime(ctx, ticketType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTicketTypeRuntime", reflect.TypeOf((*MockInventoryRepository)(nil).SetTicketTypeRuntime), ctx, ticketType)
}
