// Code generated by MockGen. DO NOT EDIT.
// Source: booking_monitor/internal/domain (interfaces: InventoryRepository)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_inventory_repository.go -package=mocks . InventoryRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInventoryRepository is a mock of InventoryRepository interface.
type MockInventoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryRepositoryMockRecorder
	isgomock struct{}
}

// MockInventoryRepositoryMockRecorder is the mock recorder for MockInventoryRepository.
type MockInventoryRepositoryMockRecorder struct {
	mock *MockInventoryRepository
}

// NewMockInventoryRepository creates a new mock instance.
func NewMockInventoryRepository(ctrl *gomock.Controller) *MockInventoryRepository {
	mock := &MockInventoryRepository{ctrl: ctrl}
	mock.recorder = &MockInventoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventoryRepository) EXPECT() *MockInventoryRepositoryMockRecorder {
	return m.recorder
}

// DeductInventory mocks base method.
func (m *MockInventoryRepository) DeductInventory(ctx context.Context, eventID, count int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeductInventory", ctx, eventID, count)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeductInventory indicates an expected call of DeductInventory.
func (mr *MockInventoryRepositoryMockRecorder) DeductInventory(ctx, eventID, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeductInventory", reflect.TypeOf((*MockInventoryRepository)(nil).DeductInventory), ctx, eventID, count)
}

// SetInventory mocks base method.
func (m *MockInventoryRepository) SetInventory(ctx context.Context, eventID, count int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetInventory", ctx, eventID, count)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetInventory indicates an expected call of SetInventory.
func (mr *MockInventoryRepositoryMockRecorder) SetInventory(ctx, eventID, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInventory", reflect.TypeOf((*MockInventoryRepository)(nil).SetInventory), ctx, eventID, count)
}
