// Code generated by MockGen. DO NOT EDIT.
// Source: order.go
//
// Generated by this command:
//
//	mockgen -source=order.go -destination=../mocks/order_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "booking_monitor/internal/domain"
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrderRepository) Create(ctx context.Context, order domain.Order) (domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, order)
	ret0, _ := ret[0].(domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOrderRepositoryMockRecorder) Create(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrderRepository)(nil).Create), ctx, order)
}

// FindStuckCharging mocks base method.
func (m *MockOrderRepository) FindStuckCharging(ctx context.Context, minAge time.Duration, limit int) ([]domain.StuckCharging, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindStuckCharging", ctx, minAge, limit)
	ret0, _ := ret[0].([]domain.StuckCharging)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindStuckCharging indicates an expected call of FindStuckCharging.
func (mr *MockOrderRepositoryMockRecorder) FindStuckCharging(ctx, minAge, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindStuckCharging", reflect.TypeOf((*MockOrderRepository)(nil).FindStuckCharging), ctx, minAge, limit)
}

// FindStuckFailed mocks base method.
func (m *MockOrderRepository) FindStuckFailed(ctx context.Context, minAge time.Duration, limit int) ([]domain.StuckFailed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindStuckFailed", ctx, minAge, limit)
	ret0, _ := ret[0].([]domain.StuckFailed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindStuckFailed indicates an expected call of FindStuckFailed.
func (mr *MockOrderRepositoryMockRecorder) FindStuckFailed(ctx, minAge, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindStuckFailed", reflect.TypeOf((*MockOrderRepository)(nil).FindStuckFailed), ctx, minAge, limit)
}

// GetByID mocks base method.
func (m *MockOrderRepository) GetByID(ctx context.Context, id uuid.UUID) (domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockOrderRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockOrderRepository)(nil).GetByID), ctx, id)
}

// ListOrders mocks base method.
func (m *MockOrderRepository) ListOrders(ctx context.Context, limit, offset int, status *domain.OrderStatus) ([]domain.Order, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrders", ctx, limit, offset, status)
	ret0, _ := ret[0].([]domain.Order)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListOrders indicates an expected call of ListOrders.
func (mr *MockOrderRepositoryMockRecorder) ListOrders(ctx, limit, offset, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrders", reflect.TypeOf((*MockOrderRepository)(nil).ListOrders), ctx, limit, offset, status)
}

// MarkAwaitingPayment mocks base method.
func (m *MockOrderRepository) MarkAwaitingPayment(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAwaitingPayment", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAwaitingPayment indicates an expected call of MarkAwaitingPayment.
func (mr *MockOrderRepositoryMockRecorder) MarkAwaitingPayment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAwaitingPayment", reflect.TypeOf((*MockOrderRepository)(nil).MarkAwaitingPayment), ctx, id)
}

// MarkCharging mocks base method.
func (m *MockOrderRepository) MarkCharging(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkCharging", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkCharging indicates an expected call of MarkCharging.
func (mr *MockOrderRepositoryMockRecorder) MarkCharging(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkCharging", reflect.TypeOf((*MockOrderRepository)(nil).MarkCharging), ctx, id)
}

// MarkCompensated mocks base method.
func (m *MockOrderRepository) MarkCompensated(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkCompensated", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkCompensated indicates an expected call of MarkCompensated.
func (mr *MockOrderRepositoryMockRecorder) MarkCompensated(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkCompensated", reflect.TypeOf((*MockOrderRepository)(nil).MarkCompensated), ctx, id)
}

// MarkConfirmed mocks base method.
func (m *MockOrderRepository) MarkConfirmed(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkConfirmed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkConfirmed indicates an expected call of MarkConfirmed.
func (mr *MockOrderRepositoryMockRecorder) MarkConfirmed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkConfirmed", reflect.TypeOf((*MockOrderRepository)(nil).MarkConfirmed), ctx, id)
}

// MarkExpired mocks base method.
func (m *MockOrderRepository) MarkExpired(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkExpired", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkExpired indicates an expected call of MarkExpired.
func (mr *MockOrderRepositoryMockRecorder) MarkExpired(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkExpired", reflect.TypeOf((*MockOrderRepository)(nil).MarkExpired), ctx, id)
}

// MarkFailed mocks base method.
func (m *MockOrderRepository) MarkFailed(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockOrderRepositoryMockRecorder) MarkFailed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockOrderRepository)(nil).MarkFailed), ctx, id)
}

// MarkPaid mocks base method.
func (m *MockOrderRepository) MarkPaid(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPaid", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPaid indicates an expected call of MarkPaid.
func (mr *MockOrderRepositoryMockRecorder) MarkPaid(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPaid", reflect.TypeOf((*MockOrderRepository)(nil).MarkPaid), ctx, id)
}

// MarkPaymentFailed mocks base method.
func (m *MockOrderRepository) MarkPaymentFailed(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPaymentFailed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPaymentFailed indicates an expected call of MarkPaymentFailed.
func (mr *MockOrderRepositoryMockRecorder) MarkPaymentFailed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPaymentFailed", reflect.TypeOf((*MockOrderRepository)(nil).MarkPaymentFailed), ctx, id)
}
