// Code generated by MockGen. DO NOT EDIT.
// Source: payment.go
//
// Generated by this command:
//
//	mockgen -source=payment.go -destination=../mocks/payment_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "booking_monitor/internal/domain"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentCharger is a mock of PaymentCharger interface.
type MockPaymentCharger struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentChargerMockRecorder
	isgomock struct{}
}

// MockPaymentChargerMockRecorder is the mock recorder for MockPaymentCharger.
type MockPaymentChargerMockRecorder struct {
	mock *MockPaymentCharger
}

// NewMockPaymentCharger creates a new mock instance.
func NewMockPaymentCharger(ctrl *gomock.Controller) *MockPaymentCharger {
	mock := &MockPaymentCharger{ctrl: ctrl}
	mock.recorder = &MockPaymentChargerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentCharger) EXPECT() *MockPaymentChargerMockRecorder {
	return m.recorder
}

// Charge mocks base method.
func (m *MockPaymentCharger) Charge(ctx context.Context, orderID uuid.UUID, amount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Charge", ctx, orderID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// Charge indicates an expected call of Charge.
func (mr *MockPaymentChargerMockRecorder) Charge(ctx, orderID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Charge", reflect.TypeOf((*MockPaymentCharger)(nil).Charge), ctx, orderID, amount)
}

// MockPaymentStatusReader is a mock of PaymentStatusReader interface.
type MockPaymentStatusReader struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentStatusReaderMockRecorder
	isgomock struct{}
}

// MockPaymentStatusReaderMockRecorder is the mock recorder for MockPaymentStatusReader.
type MockPaymentStatusReaderMockRecorder struct {
	mock *MockPaymentStatusReader
}

// NewMockPaymentStatusReader creates a new mock instance.
func NewMockPaymentStatusReader(ctrl *gomock.Controller) *MockPaymentStatusReader {
	mock := &MockPaymentStatusReader{ctrl: ctrl}
	mock.recorder = &MockPaymentStatusReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentStatusReader) EXPECT() *MockPaymentStatusReaderMockRecorder {
	return m.recorder
}

// GetStatus mocks base method.
func (m *MockPaymentStatusReader) GetStatus(ctx context.Context, orderID uuid.UUID) (domain.ChargeStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx, orderID)
	ret0, _ := ret[0].(domain.ChargeStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockPaymentStatusReaderMockRecorder) GetStatus(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockPaymentStatusReader)(nil).GetStatus), ctx, orderID)
}

// MockPaymentGateway is a mock of PaymentGateway interface.
type MockPaymentGateway struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentGatewayMockRecorder
	isgomock struct{}
}

// MockPaymentGatewayMockRecorder is the mock recorder for MockPaymentGateway.
type MockPaymentGatewayMockRecorder struct {
	mock *MockPaymentGateway
}

// NewMockPaymentGateway creates a new mock instance.
func NewMockPaymentGateway(ctrl *gomock.Controller) *MockPaymentGateway {
	mock := &MockPaymentGateway{ctrl: ctrl}
	mock.recorder = &MockPaymentGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentGateway) EXPECT() *MockPaymentGatewayMockRecorder {
	return m.recorder
}

// Charge mocks base method.
func (m *MockPaymentGateway) Charge(ctx context.Context, orderID uuid.UUID, amount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Charge", ctx, orderID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// Charge indicates an expected call of Charge.
func (mr *MockPaymentGatewayMockRecorder) Charge(ctx, orderID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Charge", reflect.TypeOf((*MockPaymentGateway)(nil).Charge), ctx, orderID, amount)
}

// GetStatus mocks base method.
func (m *MockPaymentGateway) GetStatus(ctx context.Context, orderID uuid.UUID) (domain.ChargeStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx, orderID)
	ret0, _ := ret[0].(domain.ChargeStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockPaymentGatewayMockRecorder) GetStatus(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockPaymentGateway)(nil).GetStatus), ctx, orderID)
}
