// Code generated by MockGen. DO NOT EDIT.
// Source: queue.go
//
// Generated by this command:
//
//	mockgen -source=queue.go -destination=../mocks/queue_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "booking_monitor/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrderQueue is a mock of OrderQueue interface.
type MockOrderQueue struct {
	ctrl     *gomock.Controller
	recorder *MockOrderQueueMockRecorder
	isgomock struct{}
}

// MockOrderQueueMockRecorder is the mock recorder for MockOrderQueue.
type MockOrderQueueMockRecorder struct {
	mock *MockOrderQueue
}

// NewMockOrderQueue creates a new mock instance.
func NewMockOrderQueue(ctrl *gomock.Controller) *MockOrderQueue {
	mock := &MockOrderQueue{ctrl: ctrl}
	mock.recorder = &MockOrderQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderQueue) EXPECT() *MockOrderQueueMockRecorder {
	return m.recorder
}

// EnsureGroup mocks base method.
func (m *MockOrderQueue) EnsureGroup(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureGroup", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureGroup indicates an expected call of EnsureGroup.
func (mr *MockOrderQueueMockRecorder) EnsureGroup(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureGroup", reflect.TypeOf((*MockOrderQueue)(nil).EnsureGroup), ctx)
}

// Subscribe mocks base method.
func (m *MockOrderQueue) Subscribe(ctx context.Context, handler func(context.Context, *domain.OrderMessage) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, handler)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockOrderQueueMockRecorder) Subscribe(ctx, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockOrderQueue)(nil).Subscribe), ctx, handler)
}
