// Code generated by MockGen. DO NOT EDIT.
// Source: saga_compensation.go
//
// Generated by this command:
//
//	mockgen -source=saga_compensation.go -destination=../mocks/saga_compensation_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSagaCompensationRepository is a mock of SagaCompensationRepository interface.
type MockSagaCompensationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSagaCompensationRepositoryMockRecorder
	isgomock struct{}
}

// MockSagaCompensationRepositoryMockRecorder is the mock recorder for MockSagaCompensationRepository.
type MockSagaCompensationRepositoryMockRecorder struct {
	mock *MockSagaCompensationRepository
}

// NewMockSagaCompensationRepository creates a new mock instance.
func NewMockSagaCompensationRepository(ctrl *gomock.Controller) *MockSagaCompensationRepository {
	mock := &MockSagaCompensationRepository{ctrl: ctrl}
	mock.recorder = &MockSagaCompensationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSagaCompensationRepository) EXPECT() *MockSagaCompensationRepositoryMockRecorder {
	return m.recorder
}

// MarkRedisReverted mocks base method.
func (m *MockSagaCompensationRepository) MarkRedisReverted(ctx context.Context, compensationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkRedisReverted", ctx, compensationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkRedisReverted indicates an expected call of MarkRedisReverted.
func (mr *MockSagaCompensationRepositoryMockRecorder) MarkRedisReverted(ctx, compensationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRedisReverted", reflect.TypeOf((*MockSagaCompensationRepository)(nil).MarkRedisReverted), ctx, compensationID)
}

// RecordCompletion mocks base method.
func (m *MockSagaCompensationRepository) RecordCompletion(ctx context.Context, compensationID string, orderID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordCompletion", ctx, compensationID, orderID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordCompletion indicates an expected call of RecordCompletion.
func (mr *MockSagaCompensationRepositoryMockRecorder) RecordCompletion(ctx, compensationID, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordCompletion", reflect.TypeOf((*MockSagaCompensationRepository)(nil).RecordCompletion), ctx, compensationID, orderID)
}

// WasRedisReverted mocks base method.
func (m *MockSagaCompensationRepository) WasRedisReverted(ctx context.Context, compensationID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WasRedisReverted", ctx, compensationID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WasRedisReverted indicates an expected call of WasRedisReverted.
func (mr *MockSagaCompensationRepositoryMockRecorder) WasRedisReverted(ctx, compensationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WasRedisReverted", reflect.TypeOf((*MockSagaCompensationRepository)(nil).WasRedisReverted), ctx, compensationID)
}
