// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/ticket_type.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/ticket_type.go -destination=internal/mocks/ticket_type_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "booking_monitor/internal/domain"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTicketTypeRepository is a mock of TicketTypeRepository interface.
type MockTicketTypeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTicketTypeRepositoryMockRecorder
	isgomock struct{}
}

// MockTicketTypeRepositoryMockRecorder is the mock recorder for MockTicketTypeRepository.
type MockTicketTypeRepositoryMockRecorder struct {
	mock *MockTicketTypeRepository
}

// NewMockTicketTypeRepository creates a new mock instance.
func NewMockTicketTypeRepository(ctrl *gomock.Controller) *MockTicketTypeRepository {
	mock := &MockTicketTypeRepository{ctrl: ctrl}
	mock.recorder = &MockTicketTypeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTicketTypeRepository) EXPECT() *MockTicketTypeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTicketTypeRepository) Create(ctx context.Context, t domain.TicketType) (domain.TicketType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, t)
	ret0, _ := ret[0].(domain.TicketType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTicketTypeRepositoryMockRecorder) Create(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTicketTypeRepository)(nil).Create), ctx, t)
}

// GetByID mocks base method.
func (m *MockTicketTypeRepository) GetByID(ctx context.Context, id uuid.UUID) (domain.TicketType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.TicketType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTicketTypeRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTicketTypeRepository)(nil).GetByID), ctx, id)
}

// ListByEventID mocks base method.
func (m *MockTicketTypeRepository) ListByEventID(ctx context.Context, eventID uuid.UUID) ([]domain.TicketType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByEventID", ctx, eventID)
	ret0, _ := ret[0].([]domain.TicketType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByEventID indicates an expected call of ListByEventID.
func (mr *MockTicketTypeRepositoryMockRecorder) ListByEventID(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByEventID", reflect.TypeOf((*MockTicketTypeRepository)(nil).ListByEventID), ctx, eventID)
}
